### ISSUE TITLE
Getaddrinfo failed

### ISSUE THREAD

**Issue by ResonanceForge** [nonPointer/ClashHelper#2]
报错信息：
```
Traceback (most recent call last):
  File "F:\ClashHelper-1.2.1\helper.py", line 116, in <module>
    site.purge()
  File "F:\ClashHelper-1.2.1\helper.py", line 73, in purge
    ip = socket.getaddrinfo(node['server'], None)[0][4][0]
  File "F:\Anaconda3\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno 11002] getaddrinfo failed
```
**Python:** Anaconda3

**Comment by nonPointer** [comment]
通过 socket 解析该节点的 IP 失败，应该是无效域名。已用 try-catch 修复。
